<a href="https://colab.research.google.com/github/ruthiang/Ruth_data690/blob/main/assignment_05/Handling_Missing_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Part 6-Handling Missing Data
## 3/2/2022
## Ruth Iang

In [1]:
import numpy as np
import pandas as pd

In [2]:
# missing data = empty values, or a number 0, or an invalid value(string for ex.)
falsy_values = (0, False, None, "",[], {})    # considered falsy

In [3]:
any(falsy_values)

False

In [4]:
np.nan    #behaves like virus, everything with it becomes np.nan

nan

In [5]:
3 + np.nan

nan

In [6]:
a = np.array ([1,2,3, np.nan, np.nan, 4])

In [7]:
a.sum()

nan

In [8]:
a.mean()

nan

In [9]:
a = np.array ([1,2,3, np.nan, None, 4], dtype="float")

In [10]:
a

array([ 1.,  2.,  3., nan, nan,  4.])

In [11]:
a = np.array([1, 2, 3, np.nan, np.nan, 4])

In [12]:
a.mean()

nan

In [13]:
a.sum()

nan

In [14]:
np.inf     #also behaves like virus

inf

In [15]:
3 + np.inf

inf

In [16]:
np.inf / 3

inf

In [17]:
np.inf / np.inf

nan

In [18]:
b = np.array([1, 2, 3, np.inf, np.nan, 4], dtype=np.float)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.


In [19]:
b.sum()

nan

## Checking for nan or inf

In [20]:
np.isnan(np.nan)

True

In [21]:
np.isinf(np.inf)

True

In [22]:
np.isfinite(np.nan), np.isfinite(np.inf)

(False, False)

In [23]:
np.isnan(np.array([1, 2, 3, np.nan, np.inf, 4]))

array([False, False, False,  True, False, False])

In [24]:
np.isinf(np.array([1, 2, 3, np.nan, np.inf, 4]))

array([False, False, False, False,  True, False])

In [25]:
np.isfinite(np.array([1, 2, 3, np.nan, np.inf, 4]))
# not so common to find infinite values

array([ True,  True,  True, False, False,  True])

## Filtering them out

In [26]:
a = np.array([1, 2, 3, np.nan, np.nan, 4])

In [27]:
a[~np.isnan(a)]

array([1., 2., 3., 4.])

In [28]:
# is equivalent to the code before
a[np.isfinite(a)]

array([1., 2., 3., 4.])

In [29]:
# with the result of the two codes, the following operation can be performed
a[np.isfinite(a)].sum()

10.0

In [30]:
a[np.isfinite(a)].mean()

2.5