<a href="https://colab.research.google.com/github/ruthiang/Ruth_data690/blob/main/assignment_05/Part6_Missing_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Missing Data
## 3/2/2022
## Ruth Iang

In [31]:
import numpy as np
import pandas as pd

In [32]:
# missing data = empty values, or a number 0, or an invalid value(string for ex.)
falsy_values = (0, False, None, "",[], {})    # considered falsy

In [33]:
any(falsy_values)

False

In [34]:
np.nan    #behaves like virus, everything with it becomes np.nan

nan

In [35]:
3 + np.nan

nan

In [36]:
a = np.array ([1,2,3, np.nan, np.nan, 4])

In [37]:
a.sum()

nan

In [38]:
a.mean()

nan

In [39]:
a = np.array ([1,2,3, np.nan, None, 4], dtype="float")

In [40]:
a

array([ 1.,  2.,  3., nan, nan,  4.])

In [41]:
a = np.array([1, 2, 3, np.nan, np.nan, 4])

In [42]:
a.mean()

nan

In [43]:
a.sum()

nan

In [44]:
np.inf     #also behaves like virus

inf

In [45]:
3 + np.inf

inf

In [46]:
np.inf / 3

inf

In [47]:
np.inf / np.inf

nan

In [48]:
b = np.array([1, 2, 3, np.inf, np.nan, 4], dtype=np.float)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.


In [49]:
b.sum()

nan

## Checking for nan or inf

In [50]:
np.isnan(np.nan)

True

In [51]:
np.isinf(np.inf)

True

In [52]:
np.isfinite(np.nan), np.isfinite(np.inf)

(False, False)

In [53]:
np.isnan(np.array([1, 2, 3, np.nan, np.inf, 4]))

array([False, False, False,  True, False, False])

In [54]:
np.isinf(np.array([1, 2, 3, np.nan, np.inf, 4]))

array([False, False, False, False,  True, False])

In [55]:
np.isfinite(np.array([1, 2, 3, np.nan, np.inf, 4]))
# not so common to find infinite values

array([ True,  True,  True, False, False,  True])

## Filtering them out

In [56]:
a = np.array([1, 2, 3, np.nan, np.nan, 4])

In [57]:
a[~np.isnan(a)]

array([1., 2., 3., 4.])

In [58]:
# is equivalent to the code before
a[np.isfinite(a)]

array([1., 2., 3., 4.])

In [59]:
# with the result of the two codes, the following operation can be performed
a[np.isfinite(a)].sum()

10.0

In [60]:
a[np.isfinite(a)].mean()

2.5